name: Swift Code Checks

on:
  pull_request:
    paths:
      - '.github/workflows/swift-code-checks.yml'
      - '.swiftformat.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      # Run SwiftFormat in linting mode.
      - name: SwiftFormat
        run: swift run swiftformat --lint .

  lint:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2

      # Use custom SwiftLint action for GitHub inline comments.
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
        env:
          DIFF_BASE: ${{ github.base_ref }}
